# server {
#     listen 80;

#     server_name 64.227.184.225;

#     root /usr/share/nginx/html;
#     index index.html;

#     # FRONTEND - serve static files directly
#     location / {
#         try_files $uri $uri/ /index.html;
#     }

#     # BACKEND API
#     location /api/ {
#         proxy_pass http://backend:4000;
#         proxy_http_version 1.1;
#         proxy_set_header Host $host;
#         proxy_set_header X-Real-IP $remote_addr;
#         proxy_set_header Upgrade $http_upgrade;
#         proxy_set_header Connection 'upgrade';
#     }
# }

server {
    listen 80;

    server_name 64.227.184.225;

    root /usr/share/nginx/html;
    index index.html;

    client_max_body_size 200M;

    # FRONTEND - serve static files directly
    location / {
        try_files $uri $uri/ /index.html;
    }

    # BACKEND API
    location /api/ {
        proxy_pass http://backend:4000;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
    }

    # WEBSOCKET / SOCKET.IO
    location /socket.io/ {
        proxy_pass http://backend:4000;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_cache_bypass $http_upgrade;
    }
}